import Function_1 as x

print(x.togramm(10))
print(x.toC(10))
print(*x.solve(35,94))
print(x.prime(11))
print(*x.perm("KBTU"))
x.inverse("Hello world")
print(x.tri([1,3,1,3,3]))
print(x.spy([1,2, 0, 0, 5, 7]))
print(x.vol(2.5))
print(*x.uniquelist([2, 4, 5, 4, 1, 8]))
print(x.pol("Mamma mia aim ammaM"))
x.his([1,6,8])
x.ugaday()